# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2021a545ea97faa72d7ac74eb77b78b99c48bb9721ab819ae07b68269d3bb1626a013dc12b2fc5d9a02b355ffa5089640b30306419053598425ec034746e42ea

test:
  secret_key_base: 8224a16b0d99b34187e7d654c8e9dcfde4539be8b5880c8bceed02ceef7e6b2b8a00e15f9f532e7131a8a0a04d3043bebb6d4a529ee2bce130f1a93a8045e19b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
